backend:
  name: git-gateway
  branch: master
  repo: functionfirst/kenwilsonalbums.com

media_folder: "images"
public_folder: "/images"

collections:
  - name: "news"
    label: "News"
    folder: "news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Page Name", name: "slug", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "albums"
    label: "Albums"
    folder: "albums"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Aside", name: "aside", widget: "string" }
      - { label: "Page Name", name: "slug", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Paypal Name", name: "paypal_name", widget: "string" }
      - { label: "Paypal Code", name: "paypal_code", widget: "string" }
      - { label: "Reviews", name: "reviews", widget: "markdown", default: "There are no reviews" }

  - name: "art"
    label: "Art"
    folder: "art"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Name", name: "slug", widget: "string" }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Show on homepage", name: "homepage", widget: "boolean", default: false }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "date" }

  - name: "gigs"
    label: "Gigs"
    folder: "gigs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Link to Website", name: "url", widget: "string", required: false }
      - { label: "Start Date", name: "date_start", widget: "date" }
      - { label: "End Date", name: "date_start", widget: "date", required: false }
      - label: "Type"
        name: "type"
        widget: "select"
        options:
          - { label: "Ken Wilson", value: "solo" }
          - { label: "Wilson Family", value: "wilson" }
